### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by hnklp** [hnklp/VerteMark#44]
- Chybí dotyková gesta - dva prsty pro posunutí, pinch to zoom

@KKepi

**Comment by KKepi** [comment]
**Mrknu na to v pondělí 20.5.**

**Comment by hnklp** [comment]
Ano, určitě.

**Comment by hnklp** [comment]
Otestováno, pinch to zoom funguje jak má, nefunguje ovšem scrollování do boku dvěma prsty (zleva doprava). Nahoru dolu normálně funguje.

**Comment by KKepi** [comment]
Super. Ostatní dodělám
