### ISSUE TITLE
Rozdělení TEMP složek podle názvu DICOM

### ISSUE THREAD

**Issue by hnklp** [hnklp/VerteMark#52]
- Při více instancích aplikace se budou prát o složku temp (oddělit jednotlivé anotace v TEMP do složek)

**Comment by Bumross** [comment]
Toto bude problém - budu muset pouze pojmenovat "temp" složku na základě jména zip souborů (více dicoms v jedné temp složce)

Prosím, dejte mi sem pod komentář vědět, že s touto změnou počítáte

**Comment by hnklp** [comment]
Za mě a asi i @sabinaaj (nevím, jestli někde v backendu nepoužívá názvy :-P) z pohledu GUI v pohodě. Nemělo by to nic rozbít. Prosím ještě o vyjádření @KKepi a @PalacinkaVelika

**Comment by Bumross** [comment]
Další problém - temp složka nyní funguje tak, že při extrahování nového zipu se celá přepíše. Pokud bychom každý zip extrahovali zvlášť, je problém, že budou zbytečně zaplňovat místo jednotlivé extrakce (co zip, to nová složka, která nebude mít možnost se vyprázdnit)

Nenapadá mě žádné východisko kromě toho, že bychom tento problém stornovali a uvědomil bych pana Posla o tomto problému.
Prosím všechny o nějakou myšlenku, jak bychom tento problém mohli vyřešit nebo souhlas se zrušením tohoto issue :-D

**Comment by hnklp** [comment]
Nebylo by možné složky extrahovat pro každý DICOM zvlášť a temp vypráznit při ukončení aplikace? Případně to zkombinovat s ukládáním tempu do systémové složky, která je ve Windows pod proměnnou %temp%

Tím pádem budeme složku mazat my, případně kdyby zůstal bordel, smaže ji časem samotný OS.

**Comment by hnklp** [comment]
PS: Pokud použiješ tu systémovou složku, musíš určitě použít %temp% protože v každé instalaci Windows může být složka jinde.

**Comment by Bumross** [comment]
Pardon, nepřidal jsem reguest pod issue - to mě musí prosím někdo naučit :-)
