### ISSUE TITLE
Backend - Více implantátů - Přidávání/Mazání

### ISSUE THREAD

**Issue by hnklp** [hnklp/VerteMark#54]
## Přidávání
- Každý implantát by měl mít svůj seznam souřadnic

## Mazání
- Když nebude anotováno/bude smazán dodatečný implantát, v JSONu by mělo uložené ID s hodnotou null a prázdným seznamem

@Bumross @KKepi

**Comment by KKepi** [comment]
@Bumross Jsi zítra/úterý ready vyřešit?

**Comment by sabinaaj** [comment]
Jo, to nedělejte. To ses vyřeší +- samo přidáním dalších tlačítek pro anotace.
