### ISSUE TITLE
Po dokončení všech anotcí, pokud už není možnost nic dalšího dělat, upozonit

### ISSUE THREAD

**Issue by hnklp** [hnklp/VerteMark#56]

**Comment by Bumross** [comment]
Udělám vám funkci "anyProjectAvailable" pro kontrolu "available" projektů zvlášť pro roli anotátora/validátora.

Po uložení se tato funkce zavolá a pokud vrátí hodnotu false, zobrazí se "Hurá hotovo" okénko :-)

Poprosím pouze o grafiku vyskakovacího okna a "myšlenkou", co se po tomto hlášení bude dít dál

**Comment by hnklp** [comment]
Mockrát děkuji. Úplně nevím, co si pod tím zadavatel představuje. Mě napadá udělat okénko, kde budou dvě možnosti - otevřít další soubor a nebo zrušit s tím, že se vrátí zpět do (aktuálně dokončeného) souboru.
